### ISSUE TITLE
DNS is not configured on Wi Fi adapters on Mac

### ISSUE THREAD

**Issue by ivanilves** [ivanilves/xiringuito#1]
DNS configuration is not getting properly applied on the MacOSX systems using Wi Fi.

See:
* `networksetup -getdnsservers Wi-Fi`
* `sudo networksetup -setdnsservers Wi-Fi 8.8.8.8 8.8.4.4`

**Comment by vonrabbe** [comment]
+1

**Comment by ivanilves** [comment]
https://github.com/ivanilves/xiringuito/pull/9 - solved by this PR
