### ISSUE TITLE
Packaging: RPMs, DEBs etc

### ISSUE THREAD

**Issue by ivanilves** [ivanilves/xiringuito#16]
As a xiringuito user I would like to have it packaged for my OS distribution.

*Currently I need to enter into checked out source repository before using it.*

**Comment by ivanilves** [comment]
See also: https://github.com/ivanilves/xiringuito/issues/17

**Comment by ivanilves** [comment]
https://github.com/ivanilves/xiringuito/pull/36 - not packaging but adds some "installation features"

**Comment by vonrabbe** [comment]
good!

**Comment by vonrabbe** [comment]
Any hope to get package installs? :wink:

**Comment by ivanilves** [comment]
The order is:

* https://github.com/ivanilves/xiringuito/issues/38
* https://github.com/ivanilves/xiringuito/issues/17
* this

**Comment by vonrabbe** [comment]
Will we work on this? Ping @ivanilves

**Comment by ivanilves** [comment]
Could you help me on packaging @vonrabbe ? :innocent:

**Comment by vonrabbe** [comment]
Yes I will :ok_hand:

**Comment by ivanilves** [comment]
ping @vonrabbe

**Comment by ivanilves** [comment]
I want to see it in brew! :pray:

**Comment by ivanilves** [comment]
Closing due to lack of public interest.
