### ISSUE TITLE
We need releases!

### ISSUE THREAD

**Issue by ivanilves** [ivanilves/xiringuito#17]
As a xiringuito author I would like to have tagged releases of xiringuito.

**Comment by ivanilves** [comment]
See also: https://github.com/ivanilves/xiringuito/issues/16

**Comment by vonrabbe** [comment]
What's the state here? ping @ivanilves

**Comment by ivanilves** [comment]
First https://github.com/ivanilves/xiringuito/issues/38 then this :stuck_out_tongue_winking_eye:

**Comment by vonrabbe** [comment]
https://github.com/ivanilves/xiringuito/releases
