### ISSUE TITLE
connection profiles or connection manager

### ISSUE THREAD

**Issue by vonrabbe** [ivanilves/xiringuito#19]
Could we have connection profiles in xiringito?

Typing "xiri a" and "xiri b" without full hostname would save us some time :wink:

**Comment by ivanilves** [comment]
![image](https://cloud.githubusercontent.com/assets/9897741/23624118/e53d382e-02a4-11e7-80cb-c3a22effc2a0.png)

**Comment by ivanilves** [comment]
https://github.com/ivanilves/xiringuito/pull/35 - DONE :tada:
