### ISSUE TITLE
sudo abuse on client

### ISSUE THREAD

**Issue by vonrabbe** [ivanilves/xiringuito#24]
As a xiringuito user I don't want xiringuito to call sudo command all the time, because then I need to reenter my user password on a reconnection stage which ideally should be non-interactive.

**Comment by ivanilves** [comment]
Xa xa, I know what you're talking about! Good idea, though hard to implement.

**Comment by ivanilves** [comment]
Sorry @vonrabbe after reviewing this issue more closely, I must say, we can not change application behavior the way it will not run sudo. :disappointed:

**Comment by vonrabbe** [comment]
:cry:
