### ISSUE TITLE
Reconnection is unstable (sometimes)

### ISSUE THREAD

**Issue by vonrabbe** [ivanilves/xiringuito#38]
Some work on reconnection was already done, but still we have many issues while using chiringuito on low-quality mobile networks. Could I somehow contribute to this issue? Am I the only one who experiences it?

**Comment by ivanilves** [comment]
I confirm, this happens, sometimes. Mostly on weak mobile links. :weary: 

Will work on this issue ASAP, as long as this is a "show stopper". :sweat: 

Thanks for reporting!

**Comment by ivanilves** [comment]
https://github.com/ivanilves/xiringuito/pull/41 now it is stable!

**Comment by vonrabbe** [comment]
goooooood
