### ISSUE TITLE
xaval and zsh: working directory changes

### ISSUE THREAD

**Issue by vonrabbe** [ivanilves/xiringuito#39]
Working directory gets changed to /usr/local/xiringuito when I use xaval on MacOS with zsh.

No idea why! With bash this doesn't happen. Also doesn't happen on Linux machine with zsh.

**Comment by ivanilves** [comment]
The reason: 

> Mac es una basura

:trollface: 

Nevertheless I'll try to see what it is...

**Comment by vonrabbe** [comment]
and ... ? 

is it done?
is it done?
is it done?
is it done?
is it done?
is it done?
...
is it done?

**Comment by ivanilves** [comment]
no :trollface:

**Comment by ivanilves** [comment]
![image](https://user-images.githubusercontent.com/9897741/28658751-0f7ba6c0-72ad-11e7-8a1d-e611fa4567a6.png)

**Comment by vonrabbe** [comment]
:trollface:

**Comment by ivanilves** [comment]
https://github.com/ivanilves/xiringuito/pull/48 :stuck_out_tongue_closed_eyes:

**Comment by vonrabbe** [comment]
Thank you!
