### ISSUE TITLE
Change default SSH Port

### ISSUE THREAD

**Issue by maiestro** [ivanilves/xiringuito#44]
For security reasons I changed my SSH listening port on my destination server from 22 to something above 10000.

Is there a way to connect xiringuito to a different shh ports than 22? 

Thanks a lot!

**Comment by ivanilves** [comment]
Hey @maiestro 

Could you please try: `export SSH_EXTRA_OPTS='-oPort=10000'`

And then run `xiringuito`?

Not a good way, but it could help you unless we have command line option to set SSH port. :wink:

**Comment by maiestro** [comment]
Hello @ivanilves 
It works 👍 Thanks a lot!

**Comment by vonrabbe** [comment]
solved and closed
