### ISSUE TITLE
Connect via password auth

### ISSUE THREAD

**Issue by maiestro** [ivanilves/xiringuito#45]
When I try to open a xiringuito connection, I got following auth.log information on the destination server:

> Jul 25 12:10:03 srvSup sshd[12601]: rexec line 19: Deprecated option KeyRegenerationInterval
> Jul 25 12:10:03 srvSup sshd[12601]: rexec line 20: Deprecated option ServerKeyBits
> Jul 25 12:10:03 srvSup sshd[12601]: rexec line 31: Deprecated option RSAAuthentication
> Jul 25 12:10:03 srvSup sshd[12601]: rexec line 38: Deprecated option RhostsRSAAuthentication
> Jul 25 12:10:03 srvSup sshd[12601]: reprocess config line 31: Deprecated option RSAAuthentication
> Jul 25 12:10:03 srvSup sshd[12601]: reprocess config line 38: Deprecated option RhostsRSAAuthentication

After entering the correct user password, the connection breaks immediately:

> Jul 25 12:10:15 srvSup sshd[12601]: Accepted password for supuser from xxx.xxx.xxx.xxx port 52247 ssh2
> Jul 25 12:10:15 srvSup sshd[12601]: pam_unix(sshd:session): session opened for user supuser by (uid=0)
> Jul 25 12:10:15 srvSup systemd-logind[578]: New session 1509 of user supuser.
> Jul 25 12:10:15 srvSup sshd[12607]: Received disconnect from xxx.xxx.xxx.xxx port 52247:11: disconnected by user
> Jul 25 12:10:15 srvSup sshd[12607]: Disconnected from xxx.xxx.xxx.xxx port 52247
> Jul 25 12:10:15 srvSup sshd[12601]: pam_unix(sshd:session): session closed for user supuser
> Jul 25 12:10:15 srvSup systemd-logind[578]: Removed session 1509.
> Jul 25 12:10:15 srvSup sshd[12611]: rexec line 19: Deprecated option KeyRegenerationInterval
> Jul 25 12:10:15 srvSup sshd[12611]: rexec line 20: Deprecated option ServerKeyBits
> Jul 25 12:10:15 srvSup sshd[12611]: rexec line 31: Deprecated option RSAAuthentication
> Jul 25 12:10:15 srvSup sshd[12611]: rexec line 38: Deprecated option RhostsRSAAuthentication
> Jul 25 12:10:15 srvSup sshd[12611]: reprocess config line 31: Deprecated option RSAAuthentication
> Jul 25 12:10:15 srvSup sshd[12611]: reprocess config line 38: Deprecated option RhostsRSAAuthentication

Can you give me some hints what I have done wrong? - Do I have to switch to public key auth?
Regards,
Michael

**Comment by ivanilves** [comment]
Hey @maiestro 

Due to the way `xiringuito` works, I would say, yes, you need to connect using public keys.

Sorry for inconvenience, I think I need to document this in the `README`.

**Comment by maiestro** [comment]
No problem, that works for me!
Thanks

**Comment by ivanilves** [comment]
BTW closing this :innocent:
