### ISSUE TITLE
Feature request: Replace tunctl with ip tuntap in server-execute.sh

### ISSUE THREAD

**Issue by mikatammi** [ivanilves/xiringuito#50]
uml_utilities package which contains tunctl has been dropped from Arch Linux already in 2013. This causes xiringuito to not work when connecting to a host with Arch Linux.

https://lists.archlinux.org/pipermail/aur-general/2013-May/023612.html

**Comment by ivanilves** [comment]
Hello @mikatammi 

First, sorry for delayed response. This project is fully supported, I've just been busy with rolling another one.

Second, I do not understand the issue. `xiringuito` already tries to use tuntap if tunctl is unavailable. 
Please see (for example) this: https://github.com/ivanilves/xiringuito/blob/master/scripts/server-setup.sh#L50

Could you please provide some more output/context here, so we could understand the issue better?

Thanks!

**Comment by ivanilves** [comment]
Closing this due to lack of context. But feel free to reopen! Sorry for not being able to understand U :innocent:
