### ISSUE TITLE
xaval could start xiringuito in daemon mode

### ISSUE THREAD

**Issue by alanbover** [ivanilves/xiringuito#52]
Xaval could start xiringuito in daemon mode, so you don't need to have the terminal always open.

It could be something like:

### Connect
xaval connect some-configuration

### List connection
xaval list-connections

### Drop vpn
xaval drop some-configuration

**Comment by ivanilves** [comment]
Good point @alanbover !
I think this feature would be useful.

**Comment by ivanilves** [comment]
Just to inform: 

- I've freed up all necessary time slots to implemet this feature next week.
- It will be not very hard, but I just didn't have any free time this week.

**Comment by ivanilves** [comment]
Hey, the changes are already in master!

:white_check_mark:  Passed automatic tests for Linux
:white_check_mark:  Passed manual tests for Linux
:white_check_mark:  Passed manual tests for MacOS
