### ISSUE TITLE
When no correct SSH key is available, `xaval` fails to connect without any clear error

### ISSUE THREAD

**Issue by ivanilves** [ivanilves/xiringuito#65]
When no correct SSH key is available, `xaval` fails to connect without any clear error.

### 0. 
Unload SSH key you use for connection (from **ssh-agent**) and make sure `xaval` profile (further named `myconn` in our examples) is not pointed to load keys from the filesystem (`-k` option).

### 1.
Do `xaval connect myconn` (or use interactive `xaval` prompt to connect `myconn` connection profile).

### 2.
`xaval` goes to background.

### 3.
No `xiringuito` connection is established! :scream: 

### 4.
`xaval logs myconn` gives you this output:
```
[ (client) sudo check ] 
[ (server) sudo check ] 
STATUS: DOWN
```

## Expected:
* explicit `xiringuito` error related to SSH auth should be show in `xaval` logs
* even better: `xaval` should not go to background with SSH auth failing ("probe" auth before!)

**Comment by ivanilves** [comment]
Thanks @Fsero for exposing this bug to me. 

The fix will be included in our May 2018 improvement batch, alongside with some other UX fixes and UX enhancement "`xaval` shell autocomplete".

**Comment by n1trux** [comment]
>The fix will be included in our May 2018 improvement batch

any news on this?

**Comment by ivanilvescmp** [comment]
Will try to fix it this week. This time for real! 😆

**Comment by ivanilves** [comment]
Issue fixed in https://github.com/ivanilves/xiringuito/pull/66

Tested by @vonrabbe and me - now works as expected.

Closing issue, please feel free to comment or reopen, if something.

And as always: `git pull` for the win! :triumph:
