### ISSUE TITLE
connect without root dir

### ISSUE THREAD

**Issue by l4ckyguy** [ivanilves/xiringuito#68]
can i connect without root dir on serverside?

Could not chdir to home directory /home/John3: No such file or directory

**Comment by ivanilvescmp** [comment]
well, I see no trouble, but a little code change will be required for this 🙂

**Comment by l4ckyguy** [comment]
so?..

**Comment by ivanilvescmp** [comment]
give me a few days I'll return from a trip and will take care of this 😉

**Comment by ivanilvescmp** [comment]
Hey @l4ckyguy 

I'm back with xiringuito development, however I fail to find **where** exactly this chdir failure appears and triggers any failures? 🙏 

Could you please provide more input? (logs, xiringuito output)

THANK U!
