### ISSUE TITLE
Server-side teardown is potentially broken

### ISSUE THREAD

**Issue by vonrabbe** [ivanilves/xiringuito#7]
https://github.com/ivanilves/xiringuito/blob/master/scripts/server-execute.sh#L21-L25

This will not work if you do not have root or passwordless sudo on the server.

**Comment by ivanilves** [comment]
We need to implement some reliable "reaper" on the server side.

**Comment by ivanilves** [comment]
Solved by https://github.com/ivanilves/xiringuito/pull/20
