### ISSUE TITLE
Xiringuito has no tests :(

### ISSUE THREAD

**Issue by vonrabbe** [ivanilves/xiringuito#8]
This project has no tests. And it is completely written in Bash. 
I use it, I like it, but could we do something about testing here?

**Comment by ivanilves** [comment]
Yes. We should rewrite the core script in Python some day. Testing Bash is a total disaster. :(

**Comment by ivanilves** [comment]
We could do some Docker-based testing for `xiringuito`. It would give us a clue, if we broke something or not with a news commits/PRs. Will look into it!

**Comment by vonrabbe** [comment]
see some progress here :ok_hand:

**Comment by ivanilves** [comment]
Solved! :fireworks:
